### PR TITLE
Add command 'bad' sending out invalid/out-of-order data

### PR DESCRIPTION
**Pull request by fkaleo**

### CODE REVIEW

**Comment by Dieterbe** [comment]
did you have a look at #9 ? it also has a mode to send out of order data. the code to send out of order data in this PR also creates duplicates (regardless of the duplicate option).
another thing here is that i don't like the mode name "discarded". fakemetrics just sends data, so its terminology should be about the data being sent, and be agnostic of what happens at the receiver (whoever that is, not necessarily metrictank).
furthermore i think there's a couple options related to out of order data (e.g. degree of out of orderness, in my PR 5, in yours 3, and whether to result in duplicates as in your code, or not as in mine. these could all be extra flags)

my suggestion is:
1) rebase this PR on top of #9 , keep the name `bad` instead of `discarded`. 
2) refactor the 2 modes i created in 9 to separate flags like you do in this PR, i like this idea.

this way we get 1 mode to send bad data, with all features from #9 and this PR combined, all controllable via flags.

**Comment by fkaleo** [comment]
Before submitting the PR I had a look at #9, in fact I initially rebased my work on it and had:
- my command initially called 'bad'
- taken out of order initial code from the 'ooo' command

I agree the naming 'discarded' is far from perfect, I will rename it to 'bad' and look into out of order data options; I think there is some in #5

**Comment by fkaleo** [comment]
Should be good now.

**Comment by fkaleo** [comment]
Rebased on #9

**Pull request merged**
